apiVersion: v1
kind: Service
metadata:
  name:  mfkimbell-rtp-service
  namespace: mfkimbell
spec:
  type: NodePort
  selector:
    app: mfkimbell-rtp
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000